#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 800

#define FPS 60

#define SAMURAI_FRAME_SIZE 160
#define SAMURAI_FRAME_COUNT 10
#define SAMURAI_ANIMATION_SPEED 12


#endif // CONFIG_H
